### ISSUE TITLE
CMake version too old causing issues.

### ISSUE THREAD

**Issue by chinlee1523** [vesoft-inc/nebula-cpp#103]
报错：
CMake Error at CMakeLists.txt:61 (export):
  export given OBJECT library "nebula_common_obj" which may not be exported.
Call Stack (most recent call first):
  src/CMakeLists.txt:143 (nebula_add_library)

CMake Error at CMakeLists.txt:61 (export):
  export given OBJECT library "nebula_graph_client_obj" which may not be
  exported.
Call Stack (most recent call first):
  src/CMakeLists.txt:148 (nebula_add_library)

CMake Error at CMakeLists.txt:61 (export):
  export given OBJECT library "nebula_meta_client_obj" which may not be
  exported.
Call Stack (most recent call first):
  src/CMakeLists.txt:153 (nebula_add_library)

CMake Error at CMakeLists.txt:61 (export):
  export given OBJECT library "nebula_storage_client_obj" which may not be
  exported.
Call Stack (most recent call first):
  src/CMakeLists.txt:158 (nebula_add_library)

**Comment by wey-gu** [comment]
@Shylock-Hg could you please take a look at this? thanks!

**Comment by Shylock-Hg** [comment]
What's the version?

**Comment by chinlee1523** [comment]
release-3.0

**Comment by Shylock-Hg** [comment]
> release-3.0

I can't reproduce, what's the version of cmake?

**Comment by chinlee1523** [comment]
cmake version 3.6.0

**Comment by Shylock-Hg** [comment]
> cmake version 3.6.0

I think you could try newer version.

**Comment by chinlee1523** [comment]
Please note the minimum requirements for CMAKE versions in the document.

**Comment by Shylock-Hg** [comment]
> Please note the minimum requirements for CMAKE versions in the document.

Yes, we'll update it later.

**Comment by wey-gu** [comment]
@chinlee1523 also, PR on readme to update CMAKE versions or error handling in build scripts is more than welcome, too!

Thanks for the contribution :)
