### ISSUE TITLE
Not able to make nebula client work for standalone nebula graph

### ISSUE THREAD

**Issue by cravishe** [vesoft-inc/nebula-cpp#112]
I have installed nebulagraph standalone for linux with the below mentioned installation steps. However I'm not able to make the client work.

Installation steps : [Built from source](https://docs.nebula-graph.io/3.3.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/1.install-nebula-graph-by-compiling-the-source-code/)

1. Nebulagraph (**Standalone**)
$ git clone --branch release-3.3 https://github.com/vesoft-inc/nebula.git
$ cd nebula
$ mkdir build && cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/nebula -DENABLE_TESTING=OFF -DENABLE_STANDALONE_VERSION=on - 
     DCMAKE_BUILD_TYPE=Release .. 
$ make -j2
$ sudo make install

2. Nebula cpp client
$ git clone --branch release-3.3 https://github.com/vesoft-inc/nebula-cpp.git
$ cd nebula-cpp
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make
$ sudo make install
$ sudo ldconfig

3. Start the nebula service 
$ sudo /usr/local/nebula/scripts/nebula.service start all

5. Compile example code [(**SessionExample.cpp**)](https://github.com/vesoft-inc/nebula-cpp/blob/release-3.3/examples/SessionExample.cpp)
$ LIBRARY_PATH=/usr/local/nebula/lib:$LIBRARY_PATH g++ -std=c++11 SessionExample.cpp -I/usr/local/nebula/include -lnebula_graph_client -o session_example

6. Run session_example
$ ./session_example

7. I get the below log after the above step and the program doesn't terminate (gets stuck in ConnectionPool init function)
$ Current address : 127.0.0.1:9669

**Comment by Shylock-Hg** [comment]
Can you connect to server by `nebula-console`?

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
