### ISSUE TITLE
nebula-cpp-client 当前是否有商用案例？

### ISSUE THREAD

**Issue by Winging** [vesoft-inc/nebula-cpp#31]
我们有一个服务想要在nebula graph上做测试是否可行，客户端是c++的，想咨询一下当前是否有基于nebula-cpp的实际用例，我看当前只实现了简单的sesssion 管理和执行？

**Comment by wey-gu** [comment]
@laura-ding could you share more information here?

**Comment by laura-ding** [comment]
> 我们有一个服务想要在nebula graph上做测试是否可行，客户端是c++的，想咨询一下当前是否有基于nebula-cpp的实际用例，我看当前只实现了简单的sesssion 管理和执行？

the c++ client provides the connection pool(The connection pool implementation is still simple and needs to be improved. ) and the session object and the data processing function function(in other repo nebula-common). It can basically meet the needs of users. Do you feel like there's something missing? Can you give your needs?

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
