### ISSUE TITLE
Compile option error?

### ISSUE THREAD

**Issue by Winging** [vesoft-inc/nebula-cpp#34]
https://github.com/vesoft-inc/nebula-cpp/blob/35be08ac3f41d14bd8d30962a16e5573cc481f63/examples/CMakeLists.txt#L19

I think you may want to use 
```
if (${DISABLE_CXX11_ABI} STREQUAL "ON")
```

**Comment by wey-gu** [comment]
Thank you @Winging ! Could you do a PR for this, please?

Could you help check @laura-ding?
Thanks!

**Comment by Shylock-Hg** [comment]
It's solved in https://github.com/vesoft-inc/nebula-cpp/pull/35
