### ISSUE TITLE
rpm包下载地址无效

### ISSUE THREAD

**Issue by wheelmaker0** [vesoft-inc/nebula-cpp#41]
wget https://github.com/vesoft-inc/nebula-cpp/releases/download/$release-version/nebula-graph-client-$version.$system.x86_64.rpm

release-version=2.0.0或2.0.1
system=elf7
都不行

**Comment by wey-gu** [comment]
Dear @TimeThief0723 

This is a valid link: `https://github.com/vesoft-inc/nebula-cpp/releases/download/v2.0.0/nebula-graph-client-2.0.0.el7.x86_64.rpm`

Where:
- release-version="v2.0.0"
- version="2.0.0"
- system="el7"
