### ISSUE TITLE
compiling failure, Bzip2 doesn't exist, while Bzip2 had been installed

### ISSUE THREAD

**Issue by wheelmaker0** [vesoft-inc/nebula-cpp#42]
![image](https://user-images.githubusercontent.com/4232672/124075490-827b1580-da77-11eb-9729-a08039d8fd8b.png)

**Comment by wey-gu** [comment]
Dear @laura-ding could you help check?

**Comment by laura-ding** [comment]
@TimeThief0723 
Provide the result for the output of execute `cmake` and `rpm -qa|grep bzip2`

**Comment by wey-gu** [comment]
Will close it as it's been inactive for 14 days.
