### ISSUE TITLE
compile error !No  TAsyncSocket.h

### ISSUE THREAD

**Issue by nicwh1988** [vesoft-inc/nebula-cpp#43]
Build by source code I get an error!

![image](https://user-images.githubusercontent.com/8439074/124093755-b90e5b80-da8a-11eb-9750-a0e027dcab32.png)

and  Get package from github  to build example I get an error !

![image](https://user-images.githubusercontent.com/8439074/124094074-02f74180-da8b-11eb-94a9-1aa76982349d.png)

**Comment by Shylock-Hg** [comment]
1. Please check does the third-party installed.
2. Does the package meet your environment?

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
