### ISSUE TITLE
The schema statements execution returns ok but still insert failed saying no schema found

### ISSUE THREAD

**Issue by Winging** [vesoft-inc/nebula-cpp#48]
My application needs to create graph schema online everytime. The  session.execute() function executes schema statments well and returns `nebula::ErrorCode::SUCCEEDED`. But I still fail when I invoke `session.execute()` to insert vertexes.  If I add some delay time between the two actions , it works well. It seems that there is a delay for schema creatation, what should I do to tell when could I execute insertion commands after execution of  schema statemetns?

**Comment by Shylock-Hg** [comment]
You could check the error code, retry when get ErrorCode::ERR_TAG_NOT_FOUND, ErrorCode::ERR_EDGE_NOT_FOUDN

**Comment by Winging** [comment]
> You could check the error code, retry when get ErrorCode::ERR_TAG_NOT_FOUND, ErrorCode::ERR_EDGE_NOT_FOUDN

Is there explicit method to check if schema creation is ok?  There may be some other errors when I execute insert statements imedatelly after schema creation. 
Errors found below:
```
1:
with error code: -8;Storage Error: Invalid space vid len.

2:
 error code: -12;SemanticError: No schema found for `Library'


```

**Comment by Shylock-Hg** [comment]
> > You could check the error code, retry when get ErrorCode::ERR_TAG_NOT_FOUND, ErrorCode::ERR_EDGE_NOT_FOUDN
> 
> Is there explicit method to check if schema creation is ok? There may be some other errors when I execute insert statements imedatelly after schema creation.
> Errors found below:
> 
> ```
> 1:
> with error code: -8;Storage Error: Invalid space vid len.
> 
> 2:
>  error code: -12;SemanticError: No schema found for `Library'
> ```

Or you could sleep `heartbeat_interval_secs` seconds.

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
