### ISSUE TITLE
multi  insert statments in one session execution may cause incorrect data insertion

### ISSUE THREAD

**Issue by Winging** [vesoft-inc/nebula-cpp#53]
Hi, I want to merge small insert statments into one statment and execute it in one session execution. But it results in wrong data insertion which loses some vertexes compared to one insertion statement per one session execution. 
Am I using it in the wrong way, why?
```
session.asyncexute(sql1);session.asyncexute(sql2);
-->
session.asyncexute(sql1;sql2);
```

**Comment by Shylock-Hg** [comment]
What's the error message?

**Comment by Winging** [comment]
There is no error message returned by this asyncExecute .  I suppose it may be that `The maximum number of statements allowed has been exceeded`,  because I got this error when I use nebula-console to excute the same SQL statement which contains the lost vertexes.

**Comment by Winging** [comment]
There is no error message returned by this asyncExecute .  I guess it should return `The maximum number of statements allowed has been exceeded`,  because I got this error when I use nebula-console to excute the same SQL statement which contains the lost vertexes.  What is the maximum statements allowed?

**Comment by Shylock-Hg** [comment]
> There is no error message returned by this asyncExecute . I guess it should return `The maximum number of statements allowed has been exceeded`, because I got this error when I use nebula-console to excute the same SQL statement which contains the lost vertexes. What is the maximum statements allowed?

A configuration to set the maximum number of statements in one query.

**Comment by Shylock-Hg** [comment]
You could write multiple values in one statement. And handle the error in async callback.
